version: '3.8'

#services describe the containers that will start
services:
  consumer:
    image: golang-kafka-consumer
    container_name: kafka-consumer
    build:
      context: .
      dockerfile: Dockerfile-consumer
    # Connects the API to a common base-project bridge
    networks:
      - base-project
    # If the container goes down, it will restart
    restart: "no"
    environment:
      KAFKA_URL: kafka:9092
    volumes:
      - ./logs/consumer:/root/logs
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: "200M"

  producer:
    image: golang-kafka-producer
    container_name: kafka-producer
    build:
      context: .
      dockerfile: Dockerfile-producer
    # Connects the API to a common base-project bridge
    networks:
      - base-project
    # If the container goes down, it will restart
    restart: "no"
    environment:
      KAFKA_URL: kafka:9092
    volumes:
      - ./logs/producer:/root/logs
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: "200M"

networks:
  base-project:
    external: true